### ISSUE TITLE
Sanitise data as it's stored in the state.json

### ISSUE THREAD

**Issue by B3none** [nibalizer/case-watch-bot#10]
I would say that in this case it'd probably be best to turn these strings into integers before they're stored in the `state.json`.

https://github.com/nibalizer/case-watch-bot/blob/master/example.state.json#L4

**Comment by nibalizer** [comment]
I 100% Agree with this. Having them as numbers would also allow us to add a "changed by X" value in our push notifications.

**Comment by nibalizer** [comment]
I think this is done throughout now.
